<?php

namespace Database\Seeders;

use App\Models\RefGolongan;
use App\Models\RefKategori;
use App\Models\RefRegulasi;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RefKategoriSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $refKategorisIpsi = [
            'pra usia dini' => [
                'pemasalan' => [
                    'tanding' => [
                        'FBAPA' => 'kelas bebas bawah putra',
                        'FBAPI' => 'kelas bebas bawah putri',
                        'FKAPA' => 'kelas A putra',
                        'FKAPI' => 'kelas A putri',
                        'FKBPA' => 'kelas B putra',
                        'FKBPI' => 'kelas B putri',
                        'FKCPA' => 'kelas C putra',
                        'FKCPI' => 'kelas C putri',
                        'FKDPA' => 'kelas D putra',
                        'FKDPI' => 'kelas D putri',
                        'FKEPA' => 'kelas E putra',
                        'FKEPI' => 'kelas E putri',
                        'FKFPA' => 'kelas F putra',
                        'FKFPI' => 'kelas F putri',
                        'FKGPA' => 'kelas G putra',
                        'FKGPI' => 'kelas G putri',
                        'FKHPA' => 'kelas H putra',
                        'FKHPI' => 'kelas H putri',
                        'FKIPA' => 'kelas I putra',
                        'FKIPI' => 'kelas I putri',
                        'FKJPA' => 'kelas J putra',
                        'FKJPI' => 'kelas J putri',
                        'FKKPA' => 'kelas K putra',
                        'FKKPI' => 'kelas K putri',
                        'FKLPA' => 'kelas L putra',
                        'FKLPI' => 'kelas L putri',
                        'FBAPA' => 'kelas bebas atas putra',
                        'FBAPI' => 'kelas bebas atas putri',
                    ],
                    'seni' => [
                        'TTKPA' => 'tunggal tangan kosong putra',
                        'TTKPI' => 'tunggal tangan kosong putri',
                        'TSPA' => 'tunggal bersenjata putra',
                        'TSPI' => 'tunggal bersenjata putri',
                        'TTPA' => 'solo kreatif putra',
                        'TTPI' => 'solo kreatif putri',
                    ],
                ],
            ],
            'usia dini I' => [
                'pemasalan' => [
                    'tanding' => [
                        'FKAPAA' => 'kelas bebas bawah A putra',
                        'FKAPII' => 'kelas bebas bawah A putri',
                        'FKAPAB' => 'kelas bebas bawah B putra',
                        'FKAPIB' => 'kelas bebas bawah B putri',
                        'FKAPAC' => 'kelas bebas bawah C putra',
                        'FKAPIC' => 'kelas bebas bawah C putri',
                        'FKAPA' => 'kelas A putra',
                        'FKAPI' => 'kelas A putri',
                        'FKBPA' => 'kelas B putra',
                        'FKBPI' => 'kelas B putri',
                        'FKCPA' => 'kelas C putra',
                        'FKCPI' => 'kelas C putri',
                        'FKDPA' => 'kelas D putra',
                        'FKDPI' => 'kelas D putri',
                        'FKEPA' => 'kelas E putra',
                        'FKEPI' => 'kelas E putri',
                        'FKFPA' => 'kelas F putra',
                        'FKFPI' => 'kelas F putri',
                        'FKGPA' => 'kelas G putra',
                        'FKGPI' => 'kelas G putri',
                        'FKHPA' => 'kelas H putra',
                        'FKHPI' => 'kelas H putri',
                        'FKIPA' => 'kelas I putra',
                        'FKIPI' => 'kelas I putri',
                        'FKJPA' => 'kelas J putra',
                        'FKJPI' => 'kelas J putri',
                        'FKKPA' => 'kelas K putra',
                        'FKKPI' => 'kelas K putri',
                        'FKLPA' => 'kelas L putra',
                        'FKLPI' => 'kelas L putri',
                        'FKMPA' => 'kelas M putra',
                        'FKMPI' => 'kelas M putri',
                        'FKNPA' => 'kelas N putra',
                        'FKNPI' => 'kelas N putri',
                        'FKOPA' => 'kelas O putra',
                        'FKOPI' => 'kelas O putri',
                        'FKPPA' => 'kelas P putra',
                        'FKPPI' => 'kelas P putri',
                        'FKQPA' => 'kelas Q putra',
                        'FKQPI' => 'kelas Q putri',
                        'FKRPA' => 'kelas R putra',
                        'FKRPI' => 'kelas R putri',
                        'FKSPA' => 'kelas S putra',
                        'FKSPI' => 'kelas S putri',
                        'FBAPA' => 'kelas bebas atas putra',
                        'FBAPI' => 'kelas bebas atas putri',
                    ],
                    'seni' => [
                        'TTPA1' => 'tunggal tangan kosong putra',
                        'TTPI2' => 'tunggal tangan kosong putri',
                        'TSPA3' => 'tunggal bersenjata putra',
                        'TSPI4' => 'tunggal bersenjata putri',
                        'TTPA5' => 'ganda tangan kosong putra',
                        'TTPI6' => 'ganda tangan kosong putri',
                        'TSPA7' => 'ganda bersenjata putra',
                        'TSPI8' => 'ganda bersenjata putri',
                        'TSPA9' => 'beregu putra',
                        'TSPI0' => 'beregu putri',
                        'TTPA11' => 'solo kreatif putra',
                        'TTPI12' => 'solo kreatif putri',
                    ],
                ],
            ],
            'usia dini I A' => [
                'pemasalan' => [
                    'tanding' => [
                        'FKAPAA' => 'kelas bebas bawah A putra',
                        'FKAPII' => 'kelas bebas bawah A putri',
                        'FKAPAB' => 'kelas bebas bawah B putra',
                        'FKAPIB' => 'kelas bebas bawah B putri',
                        'FKAPAC' => 'kelas bebas bawah C putra',
                        'FKAPIC' => 'kelas bebas bawah C putri',
                        'FKAPA' => 'kelas A putra',
                        'FKAPI' => 'kelas A putri',
                        'FKBPA' => 'kelas B putra',
                        'FKBPI' => 'kelas B putri',
                        'FKCPA' => 'kelas C putra',
                        'FKCPI' => 'kelas C putri',
                        'FKDPA' => 'kelas D putra',
                        'FKDPI' => 'kelas D putri',
                        'FKEPA' => 'kelas E putra',
                        'FKEPI' => 'kelas E putri',
                        'FKFPA' => 'kelas F putra',
                        'FKFPI' => 'kelas F putri',
                        'FKGPA' => 'kelas G putra',
                        'FKGPI' => 'kelas G putri',
                        'FKHPA' => 'kelas H putra',
                        'FKHPI' => 'kelas H putri',
                        'FKIPA' => 'kelas I putra',
                        'FKIPI' => 'kelas I putri',
                        'FKJPA' => 'kelas J putra',
                        'FKJPI' => 'kelas J putri',
                        'FKKPA' => 'kelas K putra',
                        'FKKPI' => 'kelas K putri',
                        'FKLPA' => 'kelas L putra',
                        'FKLPI' => 'kelas L putri',
                        'FKMPA' => 'kelas M putra',
                        'FKMPI' => 'kelas M putri',
                        'FKNPA' => 'kelas N putra',
                        'FKNPI' => 'kelas N putri',
                        'FKOPA' => 'kelas O putra',
                        'FKOPI' => 'kelas O putri',
                        'FKPPA' => 'kelas P putra',
                        'FKPPI' => 'kelas P putri',
                        'FKQPA' => 'kelas Q putra',
                        'FKQPI' => 'kelas Q putri',
                        'FKRPA' => 'kelas R putra',
                        'FKRPI' => 'kelas R putri',
                        'FKSPA' => 'kelas S putra',
                        'FKSPI' => 'kelas S putri',
                        'FBAPA' => 'kelas bebas atas putra',
                        'FBAPI' => 'kelas bebas atas putri',
                    ],
                    'seni' => [
                        'TTPA1' => 'tunggal tangan kosong putra',
                        'TTPI2' => 'tunggal tangan kosong putri',
                        'TSPA3' => 'tunggal bersenjata putra',
                        'TSPI4' => 'tunggal bersenjata putri',
                        'TTPA5' => 'ganda tangan kosong putra',
                        'TTPI6' => 'ganda tangan kosong putri',
                        'TSPA7' => 'ganda bersenjata putra',
                        'TSPI8' => 'ganda bersenjata putri',
                        'TSPA9' => 'beregu putra',
                        'TSPI0' => 'beregu putri',
                        'TTPA11' => 'solo kreatif putra',
                        'TTPI12' => 'solo kreatif putri',
                    ],
                ],
            ],
            'usia dini I B' => [
                'pemasalan' => [
                    'tanding' => [
                        'FKAPAA' => 'kelas bebas bawah A putra',
                        'FKAPII' => 'kelas bebas bawah A putri',
                        'FKAPAB' => 'kelas bebas bawah B putra',
                        'FKAPIB' => 'kelas bebas bawah B putri',
                        'FKAPAC' => 'kelas bebas bawah C putra',
                        'FKAPIC' => 'kelas bebas bawah C putri',
                        'FKAPA' => 'kelas A putra',
                        'FKAPI' => 'kelas A putri',
                        'FKBPA' => 'kelas B putra',
                        'FKBPI' => 'kelas B putri',
                        'FKCPA' => 'kelas C putra',
                        'FKCPI' => 'kelas C putri',
                        'FKDPA' => 'kelas D putra',
                        'FKDPI' => 'kelas D putri',
                        'FKEPA' => 'kelas E putra',
                        'FKEPI' => 'kelas E putri',
                        'FKFPA' => 'kelas F putra',
                        'FKFPI' => 'kelas F putri',
                        'FKGPA' => 'kelas G putra',
                        'FKGPI' => 'kelas G putri',
                        'FKHPA' => 'kelas H putra',
                        'FKHPI' => 'kelas H putri',
                        'FKIPA' => 'kelas I putra',
                        'FKIPI' => 'kelas I putri',
                        'FKJPA' => 'kelas J putra',
                        'FKJPI' => 'kelas J putri',
                        'FKKPA' => 'kelas K putra',
                        'FKKPI' => 'kelas K putri',
                        'FKLPA' => 'kelas L putra',
                        'FKLPI' => 'kelas L putri',
                        'FKMPA' => 'kelas M putra',
                        'FKMPI' => 'kelas M putri',
                        'FKNPA' => 'kelas N putra',
                        'FKNPI' => 'kelas N putri',
                        'FKOPA' => 'kelas O putra',
                        'FKOPI' => 'kelas O putri',
                        'FKPPA' => 'kelas P putra',
                        'FKPPI' => 'kelas P putri',
                        'FKQPA' => 'kelas Q putra',
                        'FKQPI' => 'kelas Q putri',
                        'FKRPA' => 'kelas R putra',
                        'FKRPI' => 'kelas R putri',
                        'FKSPA' => 'kelas S putra',
                        'FKSPI' => 'kelas S putri',
                        'FBAPA' => 'kelas bebas atas putra',
                        'FBAPI' => 'kelas bebas atas putri',
                    ],
                    'seni' => [
                        'TTPA1' => 'tunggal tangan kosong putra',
                        'TTPI2' => 'tunggal tangan kosong putri',
                        'TSPA3' => 'tunggal bersenjata putra',
                        'TSPI4' => 'tunggal bersenjata putri',
                        'TTPA5' => 'ganda tangan kosong putra',
                        'TTPI6' => 'ganda tangan kosong putri',
                        'TSPA7' => 'ganda bersenjata putra',
                        'TSPI8' => 'ganda bersenjata putri',
                        'TSPA9' => 'beregu putra',
                        'TSPI0' => 'beregu putri',
                        'TTPA11' => 'solo kreatif putra',
                        'TTPI12' => 'solo kreatif putri',
                    ],
                ],
            ],
            'usia dini II' => [
                'pemasalan' => [
                    'tanding' => [
                        'FKAPA' => 'kelas A putra',
                        'FKAPI' => 'kelas A putri',
                        'FKBPA' => 'kelas B putra',
                        'FKBPI' => 'kelas B putri',
                        'FKCPA' => 'kelas C putra',
                        'FKCPI' => 'kelas C putri',
                        'FKDPA' => 'kelas D putra',
                        'FKDPI' => 'kelas D putri',
                        'FKEPA' => 'kelas E putra',
                        'FKEPI' => 'kelas E putri',
                        'FKFPA' => 'kelas F putra',
                        'FKFPI' => 'kelas F putri',
                        'FKGPA' => 'kelas G putra',
                        'FKGPI' => 'kelas G putri',
                        'FKHPA' => 'kelas H putra',
                        'FKHPI' => 'kelas H putri',
                        'FKIPA' => 'kelas I putra',
                        'FKIPI' => 'kelas I putri',
                        'FKJPA' => 'kelas J putra',
                        'FKJPI' => 'kelas J putri',
                        'FKKPA' => 'kelas K putra',
                        'FKKPI' => 'kelas K putri',
                        'FKLPA' => 'kelas L putra',
                        'FKLPI' => 'kelas L putri',
                        'FKMPA' => 'kelas M putra',
                        'FKMPI' => 'kelas M putri',
                        'FKNPA' => 'kelas N putra',
                        'FKNPI' => 'kelas N putri',
                        'FKOPA' => 'kelas O putra',
                        'FKOPI' => 'kelas O putri',
                        'FKPPA' => 'kelas P putra',
                        'FKPPI' => 'kelas P putri',
                        'FKQPA' => 'kelas Q putra',
                        'FKQPI' => 'kelas Q putri',
                        'FKRPA' => 'kelas R putra',
                        'FKRPI' => 'kelas R putri',
                        'FKSPA' => 'kelas S putra',
                        'FKSPI' => 'kelas S putri',
                        'FBAPA' => 'kelas bebas atas putra',
                        'FBAPI' => 'kelas bebas atas putri',
                    ],
                    'seni' => [
                        'TTPA1' => 'tunggal tangan kosong putra',
                        'TTPI2' => 'tunggal tangan kosong putri',
                        'TSPA3' => 'tunggal bersenjata putra',
                        'TSPI4' => 'tunggal bersenjata putri',
                        'TTPA5' => 'ganda tangan kosong putra',
                        'TTPI6' => 'ganda tangan kosong putri',
                        'TSPA7' => 'ganda bersenjata putra',
                        'TSPI8' => 'ganda bersenjata putri',
                        'TSPA9' => 'beregu putra',
                        'TSPI0' => 'beregu putri',
                        'TTPA11' => 'solo kreatif putra',
                        'TTPI12' => 'solo kreatif putri',
                    ],
                ],
            ],
            'pra remaja' => [
                'pemasalan' => [
                    'tanding' => [
                        'FKAPA' => 'kelas A putra',
                        'FKAPI' => 'kelas A putri',
                        'FKBPA' => 'kelas B putra',
                        'FKBPI' => 'kelas B putri',
                        'FKCPA' => 'kelas C putra',
                        'FKCPI' => 'kelas C putri',
                        'FKDPA' => 'kelas D putra',
                        'FKDPI' => 'kelas D putri',
                        'FKEPA' => 'kelas E putra',
                        'FKEPI' => 'kelas E putri',
                        'FKFPA' => 'kelas F putra',
                        'FKFPI' => 'kelas F putri',
                        'FKGPA' => 'kelas G putra',
                        'FKGPI' => 'kelas G putri',
                        'FKHPA' => 'kelas H putra',
                        'FKHPI' => 'kelas H putri',
                        'FKIPA' => 'kelas I putra',
                        'FKIPI' => 'kelas I putri',
                        'FKJPA' => 'kelas J putra',
                        'FKJPI' => 'kelas J putri',
                        'FKKPA' => 'kelas K putra',
                        'FKKPI' => 'kelas K putri',
                        'FKLPA' => 'kelas L putra',
                        'FKLPI' => 'kelas L putri',
                        'FKMPA' => 'kelas M putra',
                        'FKMPI' => 'kelas M putri',
                        'FKNPA' => 'kelas N putra',
                        'FKNPI' => 'kelas N putri',
                        'FKOPA' => 'kelas O putra',
                        'FKOPI' => 'kelas O putri',
                        'FKPPA' => 'kelas P putra',
                        'FKPPI' => 'kelas P putri',
                        'FBAPA' => 'kelas bebas atas putra',
                        'FBAPI' => 'kelas bebas atas putri',
                    ],
                    'seni' => [
                        'TTPA1' => 'tunggal tangan kosong putra',
                        'TTPI2' => 'tunggal tangan kosong putri',
                        'TSPA3' => 'tunggal bersenjata putra',
                        'TSPI4' => 'tunggal bersenjata putri',
                        'TTPA5' => 'ganda tangan kosong putra',
                        'TTPI6' => 'ganda tangan kosong putri',
                        'TSPA7' => 'ganda bersenjata putra',
                        'TSPI8' => 'ganda bersenjata putri',
                        'TSPA9' => 'beregu putra',
                        'TSPI0' => 'beregu putri',
                        'TTPA11' => 'solo kreatif putra',
                        'TTPI12' => 'solo kreatif putri',
                    ],
                ],
            ],
            'remaja' => [
                'pemasalan' => [
                    'tanding' => [
                        'FBAPA' => 'kelas bebas bawah putra',
                        'FBAPI' => 'kelas bebas bawah putri',
                        'FKAPA' => 'kelas A putra',
                        'FKAPI' => 'kelas A putri',
                        'FKBPA' => 'kelas B putra',
                        'FKBPI' => 'kelas B putri',
                        'FKCPA' => 'kelas C putra',
                        'FKCPI' => 'kelas C putri',
                        'FKDPA' => 'kelas D putra',
                        'FKDPI' => 'kelas D putri',
                        'FKEPA' => 'kelas E putra',
                        'FKEPI' => 'kelas E putri',
                        'FKFPA' => 'kelas F putra',
                        'FKFPI' => 'kelas F putri',
                        'FKGPA' => 'kelas G putra',
                        'FKGPI' => 'kelas G putri',
                        'FKHPA' => 'kelas H putra',
                        'FKHPI' => 'kelas H putri',
                        'FKIPA' => 'kelas I putra',
                        'FKIPI' => 'kelas I putri',
                        'FKJPA' => 'kelas J putra',
                        'FKJPI' => 'kelas J putri',
                        'FKKPA' => 'kelas K putra',
                        'FKKPI' => 'kelas K putri',
                        'FKLPA' => 'kelas L putra',
                        'FKLPI' => 'kelas L putri',
                        'FBAPA1' => 'kelas bebas atas A putra',
                        'FBAPI1' => 'kelas bebas atas A putri',
                        'FBAPA2' => 'kelas bebas atas B putra',
                        'FBAPI2' => 'kelas bebas atas B putri',
                    ],
                    'seni' => [
                        'TTPA1' => 'tunggal tangan kosong putra',
                        'TTPI2' => 'tunggal tangan kosong putri',
                        'TSPA3' => 'tunggal bersenjata putra',
                        'TSPI4' => 'tunggal bersenjata putri',
                        'TTPA5' => 'ganda tangan kosong putra',
                        'TTPI6' => 'ganda tangan kosong putri',
                        'TSPA7' => 'ganda bersenjata putra',
                        'TSPI8' => 'ganda bersenjata putri',
                        'TSPA9' => 'beregu putra',
                        'TSPI0' => 'beregu putri',
                        'TTPA11' => 'solo kreatif putra',
                        'TTPI12' => 'solo kreatif putri',
                    ],
                ],
                'prestasi' => [
                    'tanding' => [
                        'FBAPA' => 'kelas bebas bawah putra',
                        'FBAPI' => 'kelas bebas bawah putri',
                        'FKAPA' => 'kelas A putra',
                        'FKAPI' => 'kelas A putri',
                        'FKBPA' => 'kelas B putra',
                        'FKBPI' => 'kelas B putri',
                        'FKCPA' => 'kelas C putra',
                        'FKCPI' => 'kelas C putri',
                        'FKDPA' => 'kelas D putra',
                        'FKDPI' => 'kelas D putri',
                        'FKEPA' => 'kelas E putra',
                        'FKEPI' => 'kelas E putri',
                        'FKFPA' => 'kelas F putra',
                        'FKFPI' => 'kelas F putri',
                        'FKGPA' => 'kelas G putra',
                        'FKGPI' => 'kelas G putri',
                        'FKHPA' => 'kelas H putra',
                        'FKHPI' => 'kelas H putri',
                        'FKIPA' => 'kelas I putra',
                        'FKIPI' => 'kelas I putri',
                        'FKJPA' => 'kelas J putra',
                        'FKJPI' => 'kelas J putri',
                        'FKKPA' => 'kelas K putra',
                        'FKKPI' => 'kelas K putri',
                        'FKLPA' => 'kelas L putra',
                        'FKLPI' => 'kelas L putri',
                        'FBAPA1' => 'kelas bebas atas A putra',
                        'FBAPI1' => 'kelas bebas atas A putri',
                        'FBAPA2' => 'kelas bebas atas B putra',
                        'FBAPI2' => 'kelas bebas atas B putri',
                    ],
                    'seni' => [
                        'TTPA' => 'tunggal putra',
                        'TTPI' => 'tunggal putri',
                        'TTGA' => 'ganda putra',
                        'TTGI' => 'ganda putri',
                        'TSPA' => 'beregu putra',
                        'TSPI' => 'beregu putri',
                        'TTKA' => 'solo kreatif putra',
                        'TTKI' => 'solo kreatif putri',
                    ],
                ],
            ],
            'dewasa' => [
                'pemasalan' => [
                    'tanding' => [
                        'FBAPA' => 'kelas bebas bawah putra',
                        'FBAPI' => 'kelas bebas bawah putri',
                        'FKAPA' => 'kelas A putra',
                        'FKAPI' => 'kelas A putri',
                        'FKBPA' => 'kelas B putra',
                        'FKBPI' => 'kelas B putri',
                        'FKCPA' => 'kelas C putra',
                        'FKCPI' => 'kelas C putri',
                        'FKDPA' => 'kelas D putra',
                        'FKDPI' => 'kelas D putri',
                        'FKEPA' => 'kelas E putra',
                        'FKEPI' => 'kelas E putri',
                        'FKFPA' => 'kelas F putra',
                        'FKFPI' => 'kelas F putri',
                        'FKGPA' => 'kelas G putra',
                        'FKGPI' => 'kelas G putri',
                        'FKHPA' => 'kelas H putra',
                        'FKHPI' => 'kelas H putri',
                        'FKIPA' => 'kelas I putra',
                        'FKIPI' => 'kelas I putri',
                        'FKJPA' => 'kelas J putra',
                        'FKJPI' => 'kelas J putri',
                        'FBAPA1' => 'kelas bebas atas A putra',
                        'FBAPI1' => 'kelas bebas atas A putri',
                        'FBAPA2' => 'kelas bebas atas B putra',
                        'FBAPI2' => 'kelas bebas atas B putri',
                    ],
                    'seni' => [
                        'TTPA1' => 'tunggal tangan kosong putra',
                        'TTPI2' => 'tunggal tangan kosong putri',
                        'TSPA3' => 'tunggal bersenjata putra',
                        'TSPI4' => 'tunggal bersenjata putri',
                        'TTPA5' => 'ganda tangan kosong putra',
                        'TTPI6' => 'ganda tangan kosong putri',
                        'TSPA7' => 'ganda bersenjata putra',
                        'TSPI8' => 'ganda bersenjata putri',
                        'TSPA9' => 'beregu putra',
                        'TSPI0' => 'beregu putri',
                        'TTPA11' => 'solo kreatif putra',
                        'TTPI12' => 'solo kreatif putri',
                    ],
                ],
                'prestasi' => [
                    'tanding' => [
                        'FBAPA' => 'kelas bebas bawah putra',
                        'FBAPI' => 'kelas bebas bawah putri',
                        'FKAPA' => 'kelas A putra',
                        'FKAPI' => 'kelas A putri',
                        'FKBPA' => 'kelas B putra',
                        'FKBPI' => 'kelas B putri',
                        'FKCPA' => 'kelas C putra',
                        'FKCPI' => 'kelas C putri',
                        'FKDPA' => 'kelas D putra',
                        'FKDPI' => 'kelas D putri',
                        'FKEPA' => 'kelas E putra',
                        'FKEPI' => 'kelas E putri',
                        'FKFPA' => 'kelas F putra',
                        'FKFPI' => 'kelas F putri',
                        'FKGPA' => 'kelas G putra',
                        'FKGPI' => 'kelas G putri',
                        'FKHPA' => 'kelas H putra',
                        'FKHPI' => 'kelas H putri',
                        'FKIPA' => 'kelas I putra',
                        'FKIPI' => 'kelas I putri',
                        'FKJPA' => 'kelas J putra',
                        'FKJPI' => 'kelas J putri',
                        'FKKPA' => 'kelas K putra',
                        'FKKPI' => 'kelas K putri',
                        'FKLPA' => 'kelas L putra',
                        'FKLPI' => 'kelas L putri',
                        'FBAPA1' => 'kelas bebas atas A putra',
                        'FBAPI1' => 'kelas bebas atas A putri',
                        'FBAPA2' => 'kelas bebas atas B putra',
                        'FBAPI2' => 'kelas bebas atas B putri',
                    ],
                    'seni' => [
                        'TTPA' => 'tunggal putra',
                        'TTPI' => 'tunggal putri',
                        'TTGA' => 'ganda putra',
                        'TTGI' => 'ganda putri',
                        'TSPA' => 'beregu putra',
                        'TSPI' => 'beregu putri',
                        'TTKA' => 'solo kreatif putra',
                        'TTKI' => 'solo kreatif putri',
                    ],
                ],
            ],
        ];

        // Tanding
        $regulasiIpsi = RefRegulasi::where('nama', 'IPSI 2022')->first();
        foreach ($refKategorisIpsi as $golongan => $jeniss) {
            $refGolongan = RefGolongan::where('nama', $golongan)->first();
            foreach ($jeniss as $jenis => $cabangs) {
                foreach ($cabangs as $cabang => $kategoris) {
                    foreach ($kategoris as $kode => $kategori) {
                        try {
                            RefKategori::updateOrCreate(
                                [
                                    'nama_kategori' => $kategori,
                                    'golongans_id' => $refGolongan->id,
                                    'regulasis_id' => $regulasiIpsi->id,
                                    'jenis' => $jenis,
                                    'cabang' => $cabang,
                                ],
                            );
                        } catch (\Throwable $th) {
                            dd($th->getMessage());
                        }
                    }
                }
            }
        }
    }
}
